#### Adding imports

In [30]:
import numpy as np


##### Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [31]:
integersArr = np.arange(1, 21, 3)
print(integersArr)

[ 1  4  7 10 13 16 19]


#### Create a new array of shape 3 with random numbers between 0 and 1.

In [32]:
arr = np.random.rand(3)
print(arr)

[0.0691081  0.07625474 0.78729569]


#####  4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [33]:

my_arr = np.array([
    [10, 20, 45],
    [30, 12, 16],
    [42, 17, 56]
])


first_two_rows = my_arr[:2]


last_two_rows = my_arr[1:]


print("Original Array:\n", my_arr)
print("\nFirst two rows:\n", first_two_rows)
print("\nLast two rows:\n", last_two_rows)


Original Array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows:
 [[10 20 45]
 [30 12 16]]

Last two rows:
 [[30 12 16]
 [42 17 56]]


#### 5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [34]:

array15 = np.array([[1, 2],
                   [3, 4]])

array16 = np.array([[5, 6],
                   [7, 8]])

vertical_stack = np.vstack((array15, array16))


horizontal_stack = np.hstack((array15, array16))

split_horizontally = np.hsplit(array15, 2) 


split_vertically = np.vsplit(array16, 2)  

print("The results are")
print("Array 1:\n", array15)
print("\nArray 2:\n", array16)
print("\nVertically Stacked:\n", vertical_stack)
print("\nHorizontally Stacked:\n", horizontal_stack)

print("\nSplit Array 1 Horizontally:")
for part in split_horizontally:
    print(part)

print("\nSplit Array 2 Vertically:")
for part in split_vertically:
    print(part)

The results are
Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]

Split Array 1 Horizontally:
[[1]
 [3]]
[[2]
 [4]]

Split Array 2 Vertically:
[[5 6]]
[[7 8]]


#### 6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.

#### yes the matrix multiplication is possible . Because here the number of columns in matrix x is equal to no of rows in y.

In [35]:


X = np.array([[5, 7, 2],
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2],
              [4, 2]])

result = np.dot(X, Y)

print("Result of X × Y:\n", result)


Result of X × Y:
 [[70 28]
 [70 30]
 [60 26]]


#### Case where the multiplication is not possible. So commenting the below line , for error free execution

In [36]:
# invalid_result = np.dot(Y, X)
# print(invalid_result)

####  7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [37]:

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Original vector x:", x)
print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)

x_reshaped = x.reshape(3, 1)
print("\nReshaped x to (3,1):\n", x_reshaped)
print("Shape of reshaped x:", x_reshaped.shape)
print("Number of dimensions of reshaped x:", x_reshaped.ndim)

y_reshaped = y.reshape(3, 1)
print("\nReshaped y to (3,1):\n", y_reshaped)
print("Shape of reshaped y:", y_reshaped.shape)
print("Number of dimensions of reshaped y:", y_reshaped.ndim)


Original vector x: [ 2 -1 -8]
Shape of x: (3,)
Number of dimensions of x: 1

Reshaped x to (3,1):
 [[ 2]
 [-1]
 [-8]]
Shape of reshaped x: (3, 1)
Number of dimensions of reshaped x: 2

Reshaped y to (3,1):
 [[ 3]
 [ 1]
 [-2]]
Shape of reshaped y: (3, 1)
Number of dimensions of reshaped y: 2


##### It helps in operation between arrays of different sizes by automatically expanding the smaller one 

In [38]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

vector = np.array([1, 2, 3])


sub_result = matrix - vector


mul_result = matrix * vector

print("Original Matrix:\n", matrix)
print("\nVector:\n", vector)
print("\nMatrix - Vector (Broadcasted Subtraction):\n", sub_result)
print("\nMatrix * Vector (Broadcasted Multiplication):\n", mul_result)



Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector:
 [1 2 3]

Matrix - Vector (Broadcasted Subtraction):
 [[0 0 0]
 [3 3 3]
 [6 6 6]]

Matrix * Vector (Broadcasted Multiplication):
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


#####  9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each). 

- Line Plot: it  represents the data on a continuous scale by connecting different points on a single line.

- Scatter Plot: Represents the connection between two  values in which each dot represents a different data point.  

- Bar Chart: Uses bars whose lengths correspond to their values to highlight at particular gaps.

- Histogram: Grouping values into bons and displaying how many data points fall into each bin.

##### Part-B

In [39]:


coeff_matrix = np.array([[2, 3, -4],
                         [1, -4, 0]])

rhs_vector = np.array([6, 8])


solution_vector, residuals, rank_A, singular_values = np.linalg.lstsq(coeff_matrix, rhs_vector, rcond=None)


augmented_matrix = np.hstack((coeff_matrix, rhs_vector.reshape(-1, 1)))


rank_augmented = np.linalg.matrix_rank(augmented_matrix)

x1, x2, x3 = solution_vector


print("The value of x1 is:", x1)
print("The value of x2 is:", x2)
print("The value of x3 is:", x3)
print("Residuals:", residuals)
print("Rank of coefficient matrix (A):", rank_A)
print("Rank of augmented matrix [A|b]:", rank_augmented)

if rank_A == rank_augmented:
    if rank_A < coeff_matrix.shape[1]:
        print(" Infinite solutions")
    else:
        print(" Unique solution")
else:
    print("No solution")

The value of x1 is: 1.669211195928752
The value of x2 is: -1.5826972010178109
The value of x3 is: -1.852417302798981
Residuals: []
Rank of coefficient matrix (A): 2
Rank of augmented matrix [A|b]: 2
 Infinite solutions


In [40]:

coeff_matrix = np.array([[3, -4, 5],
                         [-1, 2, -4]])


rhs_vector = np.array([10, 8])


solution_vector, residuals, rank_coeff, singular_values = np.linalg.lstsq(coeff_matrix, rhs_vector, rcond=None)


augmented_matrix = np.hstack((coeff_matrix, rhs_vector.reshape(-1, 1)))


rank_augmented = np.linalg.matrix_rank(augmented_matrix)


y1, y2, y3 = solution_vector


print("The value of y1 is:", y1)
print("The value of y2 is:", y2)
print("The value of y3 is:", y3)
print("Residuals:", residuals)
print("Rank of coefficient matrix (A):", rank_coeff)
print("Rank of augmented matrix [A|b]:", rank_augmented)


if rank_coeff == rank_augmented:
    if rank_coeff < coeff_matrix.shape[1]:
        print("Infinite solutions")
    else:
        print("Unique solution")
else:
    print("No solution")

The value of y1 is: 7.460674157303374
The value of y2 is: -4.629213483146074
The value of y3 is: -6.179775280898881
Residuals: []
Rank of coefficient matrix (A): 2
Rank of augmented matrix [A|b]: 2
Infinite solutions
